package com.nativeframe.kotlin.intl.android

import android.util.Log

/**
 * Logs each country with their drawable
 */
@Suppress("unused")
fun logCountriesWithDrawables() {
    val sb = StringBuilder()
    for (c in COUNTRIES) {
        sb.appendLine("Country(\"${c.code}\", \"${c.name}\", ${c.dialCode}, R.drawable.country_flag_${c.code}),")
    }

    Log.i("KotlinIntlAndroid", sb.toString())
}

/**
 * All supported countries
 */
val COUNTRIES = arrayOf(
    Country("af", "Afghanistan (‫افغانستان‬‎)", 93, R.drawable.country_flag_af),
    Country("al", "Albania (Shqipëri)", 355, R.drawable.country_flag_al),
    Country("dz", "Algeria (‫الجزائر‬‎)", 213, R.drawable.country_flag_dz),
    Country("as", "American Samoa", 1684, R.drawable.country_flag_as),
    Country("ad", "Andorra", 376, R.drawable.country_flag_ad),
    Country("ao", "Angola", 244, R.drawable.country_flag_ao),
    Country("ai", "Anguilla", 1264, R.drawable.country_flag_ai),
    Country("ag", "Antigua and Barbuda", 1268, R.drawable.country_flag_ag),
    Country("ar", "Argentina", 54, R.drawable.country_flag_ar),
    Country("am", "Armenia (Հայաստան)", 374, R.drawable.country_flag_am),
    Country("aw", "Aruba", 297, R.drawable.country_flag_aw),
    Country("au", "Australia", 61, R.drawable.country_flag_au),
    Country("at", "Austria (Österreich)", 43, R.drawable.country_flag_at),
    Country("az", "Azerbaijan (Azərbaycan)", 994, R.drawable.country_flag_az),
    Country("bs", "Bahamas", 1242, R.drawable.country_flag_bs),
    Country("bh", "Bahrain (‫البحرين‬‎)", 973, R.drawable.country_flag_bh),
    Country("bd", "Bangladesh (বাংলাদেশ)", 880, R.drawable.country_flag_bd),
    Country("bb", "Barbados", 1246, R.drawable.country_flag_bb),
    Country("by", "Belarus (Беларусь)", 375, R.drawable.country_flag_by),
    Country("be", "Belgium (België)", 32, R.drawable.country_flag_be),
    Country("bz", "Belize", 501, R.drawable.country_flag_bz),
    Country("bj", "Benin (Bénin)", 229, R.drawable.country_flag_bj),
    Country("bm", "Bermuda", 1441, R.drawable.country_flag_bm),
    Country("bt", "Bhutan (འབྲུག)", 975, R.drawable.country_flag_bt),
    Country("bo", "Bolivia", 591, R.drawable.country_flag_bo),
    Country("ba", "Bosnia and Herzegovina (Босна и Херцеговина)", 387, R.drawable.country_flag_ba),
    Country("bw", "Botswana", 267, R.drawable.country_flag_bw),
    Country("br", "Brazil (Brasil)", 55, R.drawable.country_flag_br),
    Country("io", "British Indian Ocean Territory", 246, R.drawable.country_flag_io),
    Country("vg", "British Virgin Islands", 1284, R.drawable.country_flag_vg),
    Country("bn", "Brunei", 673, R.drawable.country_flag_bn),
    Country("bg", "Bulgaria (България)", 359, R.drawable.country_flag_bg),
    Country("bf", "Burkina Faso", 226, R.drawable.country_flag_bf),
    Country("bi", "Burundi (Uburundi)", 257, R.drawable.country_flag_bi),
    Country("kh", "Cambodia (កម្ពុជា)", 855, R.drawable.country_flag_kh),
    Country("cm", "Cameroon (Cameroun)", 237, R.drawable.country_flag_cm),
    Country("ca", "Canada", 1, R.drawable.country_flag_ca),
    Country("cv", "Cape Verde (Kabu Verdi)", 238, R.drawable.country_flag_cv),
    Country("bq", "Caribbean Netherlands", 599, R.drawable.country_flag_bq),
    Country("ky", "Cayman Islands", 1345, R.drawable.country_flag_ky),
    Country(
        "cf",
        "Central African Republic (République centrafricaine)",
        236,
        R.drawable.country_flag_cf
    ),
    Country("td", "Chad (Tchad)", 235, R.drawable.country_flag_td),
    Country("cl", "Chile", 56, R.drawable.country_flag_cl),
    Country("cn", "China (中国)", 86, R.drawable.country_flag_cn),
    Country("cx", "Christmas Island", 61, R.drawable.country_flag_cx),
    Country("cc", "Cocos (Keeling) Islands", 61, R.drawable.country_flag_cc),
    Country("co", "Colombia", 57, R.drawable.country_flag_co),
    Country("km", "Comoros (‫جزر القمر‬‎)", 269, R.drawable.country_flag_km),
    Country(
        "cd",
        "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
        243,
        R.drawable.country_flag_cd
    ),
    Country("cg", "Congo (Republic) (Congo-Brazzaville)", 242, R.drawable.country_flag_cg),
    Country("ck", "Cook Islands", 682, R.drawable.country_flag_ck),
    Country("cr", "Costa Rica", 506, R.drawable.country_flag_cr),
    Country("ci", "Côte d’Ivoire", 225, R.drawable.country_flag_ci),
    Country("hr", "Croatia (Hrvatska)", 385, R.drawable.country_flag_hr),
    Country("cu", "Cuba", 53, R.drawable.country_flag_cu),
    Country("cw", "Curaçao", 599, R.drawable.country_flag_cw),
    Country("cy", "Cyprus (Κύπρος)", 357, R.drawable.country_flag_cy),
    Country("cz", "Czech Republic (Česká republika)", 420, R.drawable.country_flag_cz),
    Country("dk", "Denmark (Danmark)", 45, R.drawable.country_flag_dk),
    Country("dj", "Djibouti", 253, R.drawable.country_flag_dj),
    Country("dm", "Dominica", 1767, R.drawable.country_flag_dm),
    Country("do", "Dominican Republic (República Dominicana)", 1, R.drawable.country_flag_do),
    Country("ec", "Ecuador", 593, R.drawable.country_flag_ec),
    Country("eg", "Egypt (‫مصر‬‎)", 20, R.drawable.country_flag_eg),
    Country("sv", "El Salvador", 503, R.drawable.country_flag_sv),
    Country("gq", "Equatorial Guinea (Guinea Ecuatorial)", 240, R.drawable.country_flag_gq),
    Country("er", "Eritrea", 291, R.drawable.country_flag_er),
    Country("ee", "Estonia (Eesti)", 372, R.drawable.country_flag_ee),
    Country("et", "Ethiopia", 251, R.drawable.country_flag_et),
    Country("fk", "Falkland Islands (Islas Malvinas)", 500, R.drawable.country_flag_fk),
    Country("fo", "Faroe Islands (Føroyar)", 298, R.drawable.country_flag_fo),
    Country("fj", "Fiji", 679, R.drawable.country_flag_fj),
    Country("fi", "Finland (Suomi)", 358, R.drawable.country_flag_fi),
    Country("fr", "France", 33, R.drawable.country_flag_fr),
    Country("gf", "French Guiana (Guyane française)", 594, R.drawable.country_flag_gf),
    Country("pf", "French Polynesia (Polynésie française)", 689, R.drawable.country_flag_pf),
    Country("ga", "Gabon", 241, R.drawable.country_flag_ga),
    Country("gm", "Gambia", 220, R.drawable.country_flag_gm),
    Country("ge", "Georgia (საქართველო)", 995, R.drawable.country_flag_ge),
    Country("de", "Germany (Deutschland)", 49, R.drawable.country_flag_de),
    Country("gh", "Ghana (Gaana)", 233, R.drawable.country_flag_gh),
    Country("gi", "Gibraltar", 350, R.drawable.country_flag_gi),
    Country("gr", "Greece (Ελλάδα)", 30, R.drawable.country_flag_gr),
    Country("gl", "Greenland (Kalaallit Nunaat)", 299, R.drawable.country_flag_gl),
    Country("gd", "Grenada", 1473, R.drawable.country_flag_gd),
    Country("gp", "Guadeloupe", 590, R.drawable.country_flag_gp),
    Country("gu", "Guam", 1671, R.drawable.country_flag_gu),
    Country("gt", "Guatemala", 502, R.drawable.country_flag_gt),
    Country("gg", "Guernsey", 44, R.drawable.country_flag_gg),
    Country("gn", "Guinea (Guinée)", 224, R.drawable.country_flag_gn),
    Country("gw", "Guinea-Bissau (Guiné Bissau)", 245, R.drawable.country_flag_gw),
    Country("gy", "Guyana", 592, R.drawable.country_flag_gy),
    Country("ht", "Haiti", 509, R.drawable.country_flag_ht),
    Country("hn", "Honduras", 504, R.drawable.country_flag_hn),
    Country("hk", "Hong Kong (香港)", 852, R.drawable.country_flag_hk),
    Country("hu", "Hungary (Magyarország)", 36, R.drawable.country_flag_hu),
    Country("is", "Iceland (Ísland)", 354, R.drawable.country_flag_is),
    Country("in", "India (भारत)", 91, R.drawable.country_flag_in),
    Country("id", "Indonesia", 62, R.drawable.country_flag_id),
    Country("ir", "Iran (‫ایران‬‎)", 98, R.drawable.country_flag_ir),
    Country("iq", "Iraq (‫العراق‬‎)", 964, R.drawable.country_flag_iq),
    Country("ie", "Ireland", 353, R.drawable.country_flag_ie),
    Country("im", "Isle of Man", 44, R.drawable.country_flag_im),
    Country("il", "Israel (‫ישראל‬‎)", 972, R.drawable.country_flag_il),
    Country("it", "Italy (Italia)", 39, R.drawable.country_flag_it),
    Country("jm", "Jamaica", 1876, R.drawable.country_flag_jm),
    Country("jp", "Japan (日本)", 81, R.drawable.country_flag_jp),
    Country("je", "Jersey", 44, R.drawable.country_flag_je),
    Country("jo", "Jordan (‫الأردن‬‎)", 962, R.drawable.country_flag_jo),
    Country("kz", "Kazakhstan (Казахстан)", 7, R.drawable.country_flag_kz),
    Country("ke", "Kenya", 254, R.drawable.country_flag_ke),
    Country("ki", "Kiribati", 686, R.drawable.country_flag_ki),
    Country("kw", "Kuwait (‫الكويت‬‎)", 965, R.drawable.country_flag_kw),
    Country("kg", "Kyrgyzstan (Кыргызстан)", 996, R.drawable.country_flag_kg),
    Country("la", "Laos (ລາວ)", 856, R.drawable.country_flag_la),
    Country("lv", "Latvia (Latvija)", 371, R.drawable.country_flag_lv),
    Country("lb", "Lebanon (‫لبنان‬‎)", 961, R.drawable.country_flag_lb),
    Country("ls", "Lesotho", 266, R.drawable.country_flag_ls),
    Country("lr", "Liberia", 231, R.drawable.country_flag_lr),
    Country("ly", "Libya (‫ليبيا‬‎)", 218, R.drawable.country_flag_ly),
    Country("li", "Liechtenstein", 423, R.drawable.country_flag_li),
    Country("lt", "Lithuania (Lietuva)", 370, R.drawable.country_flag_lt),
    Country("lu", "Luxembourg", 352, R.drawable.country_flag_lu),
    Country("mo", "Macau (澳門)", 853, R.drawable.country_flag_mo),
    Country("mk", "Macedonia (FYROM) (Македонија)", 389, R.drawable.country_flag_mk),
    Country("mg", "Madagascar (Madagasikara)", 261, R.drawable.country_flag_mg),
    Country("mw", "Malawi", 265, R.drawable.country_flag_mw),
    Country("my", "Malaysia", 60, R.drawable.country_flag_my),
    Country("mv", "Maldives", 960, R.drawable.country_flag_mv),
    Country("ml", "Mali", 223, R.drawable.country_flag_ml),
    Country("mt", "Malta", 356, R.drawable.country_flag_mt),
    Country("mh", "Marshall Islands", 692, R.drawable.country_flag_mh),
    Country("mq", "Martinique", 596, R.drawable.country_flag_mq),
    Country("mr", "Mauritania (‫موريتانيا‬‎)", 222, R.drawable.country_flag_mr),
    Country("mu", "Mauritius (Moris)", 230, R.drawable.country_flag_mu),
    Country("yt", "Mayotte", 262, R.drawable.country_flag_yt),
    Country("mx", "Mexico (México)", 52, R.drawable.country_flag_mx),
    Country("fm", "Micronesia", 691, R.drawable.country_flag_fm),
    Country("md", "Moldova (Republica Moldova)", 373, R.drawable.country_flag_md),
    Country("mc", "Monaco", 377, R.drawable.country_flag_mc),
    Country("mn", "Mongolia (Монгол)", 976, R.drawable.country_flag_mn),
    Country("me", "Montenegro (Crna Gora)", 382, R.drawable.country_flag_me),
    Country("ms", "Montserrat", 1664, R.drawable.country_flag_ms),
    Country("ma", "Morocco (‫المغرب‬‎)", 212, R.drawable.country_flag_ma),
    Country("mz", "Mozambique (Moçambique)", 258, R.drawable.country_flag_mz),
    Country("mm", "Myanmar (Burma) (မြန်မာ)", 95, R.drawable.country_flag_mm),
    Country("na", "Namibia (Namibië)", 264, R.drawable.country_flag_na),
    Country("nr", "Nauru", 674, R.drawable.country_flag_nr),
    Country("np", "Nepal (नेपाल)", 977, R.drawable.country_flag_np),
    Country("nl", "Netherlands (Nederland)", 31, R.drawable.country_flag_nl),
    Country("nc", "New Caledonia (Nouvelle-Calédonie)", 687, R.drawable.country_flag_nc),
    Country("nz", "New Zealand", 64, R.drawable.country_flag_nz),
    Country("ni", "Nicaragua", 505, R.drawable.country_flag_ni),
    Country("ne", "Niger (Nijar)", 227, R.drawable.country_flag_ne),
    Country("ng", "Nigeria", 234, R.drawable.country_flag_ng),
    Country("nu", "Niue", 683, R.drawable.country_flag_nu),
    Country("nf", "Norfolk Island", 672, R.drawable.country_flag_nf),
    Country("kp", "North Korea (조선 민주주의 인민 공화국)", 850, R.drawable.country_flag_kp),
    Country("mp", "Northern Mariana Islands", 1670, R.drawable.country_flag_mp),
    Country("no", "Norway (Norge)", 47, R.drawable.country_flag_no),
    Country("om", "Oman (‫عُمان‬‎)", 968, R.drawable.country_flag_om),
    Country("pk", "Pakistan (‫پاکستان‬‎)", 92, R.drawable.country_flag_pk),
    Country("pw", "Palau", 680, R.drawable.country_flag_pw),
    Country("ps", "Palestine (‫فلسطين‬‎)", 970, R.drawable.country_flag_ps),
    Country("pa", "Panama (Panamá)", 507, R.drawable.country_flag_pa),
    Country("pg", "Papua New Guinea", 675, R.drawable.country_flag_pg),
    Country("py", "Paraguay", 595, R.drawable.country_flag_py),
    Country("pe", "Peru (Perú)", 51, R.drawable.country_flag_pe),
    Country("ph", "Philippines", 63, R.drawable.country_flag_ph),
    Country("pl", "Poland (Polska)", 48, R.drawable.country_flag_pl),
    Country("pt", "Portugal", 351, R.drawable.country_flag_pt),
    Country("pr", "Puerto Rico", 1, R.drawable.country_flag_pr),
    Country("qa", "Qatar (‫قطر‬‎)", 974, R.drawable.country_flag_qa),
    Country("re", "Réunion (La Réunion)", 262, R.drawable.country_flag_re),
    Country("ro", "Romania (România)", 40, R.drawable.country_flag_ro),
    Country("ru", "Russia (Россия)", 7, R.drawable.country_flag_ru),
    Country("rw", "Rwanda", 250, R.drawable.country_flag_rw),
    Country("bl", "Saint Barthélemy (Saint-Barthélemy)", 590, R.drawable.country_flag_bl),
    Country("sh", "Saint Helena", 290, R.drawable.country_flag_sh),
    Country("kn", "Saint Kitts and Nevis", 1869, R.drawable.country_flag_kn),
    Country("lc", "Saint Lucia", 1758, R.drawable.country_flag_lc),
    Country(
        "mf",
        "Saint Martin (Saint-Martin (partie française))",
        590,
        R.drawable.country_flag_mf
    ),
    Country(
        "pm",
        "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
        508,
        R.drawable.country_flag_pm
    ),
    Country("vc", "Saint Vincent and the Grenadines", 1784, R.drawable.country_flag_vc),
    Country("ws", "Samoa", 685, R.drawable.country_flag_ws),
    Country("sm", "San Marino", 378, R.drawable.country_flag_sm),
    Country("st", "São Tomé and Príncipe (São Tomé e Príncipe)", 239, R.drawable.country_flag_st),
    Country("sa", "Saudi Arabia (‫المملكة العربية السعودية‬‎)", 966, R.drawable.country_flag_sa),
    Country("sn", "Senegal (Sénégal)", 221, R.drawable.country_flag_sn),
    Country("rs", "Serbia (Србија)", 381, R.drawable.country_flag_rs),
    Country("sc", "Seychelles", 248, R.drawable.country_flag_sc),
    Country("sl", "Sierra Leone", 232, R.drawable.country_flag_sl),
    Country("sg", "Singapore", 65, R.drawable.country_flag_sg),
    Country("sx", "Sint Maarten", 1721, R.drawable.country_flag_sx),
    Country("sk", "Slovakia (Slovensko)", 421, R.drawable.country_flag_sk),
    Country("si", "Slovenia (Slovenija)", 386, R.drawable.country_flag_si),
    Country("sb", "Solomon Islands", 677, R.drawable.country_flag_sb),
    Country("so", "Somalia (Soomaaliya)", 252, R.drawable.country_flag_so),
    Country("za", "South Africa", 27, R.drawable.country_flag_za),
    Country("kr", "South Korea (대한민국)", 82, R.drawable.country_flag_kr),
    Country("ss", "South Sudan (‫جنوب السودان‬‎)", 211, R.drawable.country_flag_ss),
    Country("es", "Spain (España)", 34, R.drawable.country_flag_es),
    Country("lk", "Sri Lanka (ශ්‍රී ලංකාව)", 94, R.drawable.country_flag_lk),
    Country("sd", "Sudan (‫السودان‬‎)", 249, R.drawable.country_flag_sd),
    Country("sr", "Suriname", 597, R.drawable.country_flag_sr),
    Country("sj", "Svalbard and Jan Mayen", 47, R.drawable.country_flag_sj),
    Country("sz", "Swaziland", 268, R.drawable.country_flag_sz),
    Country("se", "Sweden (Sverige)", 46, R.drawable.country_flag_se),
    Country("ch", "Switzerland (Schweiz)", 41, R.drawable.country_flag_ch),
    Country("sy", "Syria (‫سوريا‬‎)", 963, R.drawable.country_flag_sy),
    Country("tw", "Taiwan (台灣)", 886, R.drawable.country_flag_tw),
    Country("tj", "Tajikistan", 992, R.drawable.country_flag_tj),
    Country("tz", "Tanzania", 255, R.drawable.country_flag_tz),
    Country("th", "Thailand (ไทย)", 66, R.drawable.country_flag_th),
    Country("tl", "Timor-Leste", 670, R.drawable.country_flag_tl),
    Country("tg", "Togo", 228, R.drawable.country_flag_tg),
    Country("tk", "Tokelau", 690, R.drawable.country_flag_tk),
    Country("to", "Tonga", 676, R.drawable.country_flag_to),
    Country("tt", "Trinidad and Tobago", 1868, R.drawable.country_flag_tt),
    Country("tn", "Tunisia (‫تونس‬‎)", 216, R.drawable.country_flag_tn),
    Country("tr", "Turkey (Türkiye)", 90, R.drawable.country_flag_tr),
    Country("tm", "Turkmenistan", 993, R.drawable.country_flag_tm),
    Country("tc", "Turks and Caicos Islands", 1649, R.drawable.country_flag_tc),
    Country("tv", "Tuvalu", 688, R.drawable.country_flag_tv),
    Country("vi", "U.S. Virgin Islands", 1340, R.drawable.country_flag_vi),
    Country("ug", "Uganda", 256, R.drawable.country_flag_ug),
    Country("ua", "Ukraine (Україна)", 380, R.drawable.country_flag_ua),
    Country(
        "ae",
        "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
        971,
        R.drawable.country_flag_ae
    ),
    Country("gb", "United Kingdom", 44, R.drawable.country_flag_gb),
    Country("us", "United States", 1, R.drawable.country_flag_us),
    Country("uy", "Uruguay", 598, R.drawable.country_flag_uy),
    Country("uz", "Uzbekistan (Oʻzbekiston)", 998, R.drawable.country_flag_uz),
    Country("vu", "Vanuatu", 678, R.drawable.country_flag_vu),
    Country("va", "Vatican City (Città del Vaticano)", 39, R.drawable.country_flag_va),
    Country("ve", "Venezuela", 58, R.drawable.country_flag_ve),
    Country("vn", "Vietnam (Việt Nam)", 84, R.drawable.country_flag_vn),
    Country("wf", "Wallis and Futuna", 681, R.drawable.country_flag_wf),
    Country("eh", "Western Sahara (‫الصحراء الغربية‬‎)", 212, R.drawable.country_flag_eh),
    Country("ye", "Yemen (‫اليمن‬‎)", 967, R.drawable.country_flag_ye),
    Country("zm", "Zambia", 260, R.drawable.country_flag_zm),
    Country("zw", "Zimbabwe", 263, R.drawable.country_flag_zw),
    Country("ax", "Åland Islands", 358, R.drawable.country_flag_ax),
)